spring:
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://host.docker.internal:${MYSQL_EXTERNAL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: ${MYSQL_DATABASE}
    hibernate:
      ddl-auto: update

api.security.token.secret: mytoken